name: amgad_business_card
description: "Amgad's online business card"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

# to use flutter gen => dart run build_runner build
# to delete conflicts => dart run build_runner build --delete-conflicting-outputs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
